package org.csuc.typesafe.semantics;

/**
 * @author amartinez
 */
public enum ClassId {

    AUTHOR,
    BOOK,
    CHAPTER_IN_BOOK,
    CHECKED,
    CO_INVESTIGATOR,
    DEPARTMENT_CODE_1,
    DEPARTMENT_CODE_2,
    DEPARTMENT_OR_INSTITUTE,
    DEPARTMENT_OR_INSTITUTE_CODE,
    DIRECTOR,
    DISS_DIRECTOR,
    DOI,
    EMAIL,
    FUNDING_PROGRAMME,
    FUNDING_PROGRAMME_CODE,
    GROUP_AUTHORS,
    GROUP_LEADER,
    HANDLE,
    INTERNAL_PROJECT_CODE,
    ISSN,
    JOURNAL,
    JOURNAL_ARTICLE,
    MEMBER,
    OFFICIAL_PROJECT_CODE,
    ORCID,
    ORGANISATION_LEGAL_POSTAL_ADDRESS,
    ORIGINATOR,
    PHD_THESIS,
    PHONE,
    PRESENTED_NAME,
    PRINCIPAL_INVESTIGATOR,
    PUBLISHER,
    REGIONAL_RESEARCH_GROUP_CODE,
    RESEARCH_GROUP,
    RESEARCH_GROUP_CREATION_DATE,
    RESEARCH_GROUP_INTERNAL_CODE,
    RESEARCHER,
    SIGNATURE,
    UNCHECKED,
    UNIVERSITY_CODE,
    UNIVERSITY_PRESS;
}
