package org.csuc.typesafe.semantics;

/**
 * @author amartinez
 */
public enum SchemeId {

    FUNDING_SOURCE_TYPES,
    IDENTIFIER_TYPES,
    ORGANISATION_CONTACT_DETAILS,
    ORGANISATION_OUTPUT_CONTRIBUTIONS,
    ORGANISATION_RESEARCH_INFRASTRUCTURE_ROLES,
    ORGANISATION_TYPES,
    OUTPUT_TYPES,
    PERSON_CONTACT_DETAILS,
    PERSON_NAMES,
    PERSON_ORGANISATION_ROLES,
    PERSON_OUTPUT_CONTRIBUTIONS,
    PERSON_PROFESSIONAL_RELATIONSHIPS,
    PERSON_PROJECT_ENGAGEMENTS,
    PROJECT_OUTPUT_ROLES,
    VERIFICATION_STATUSES;

}
