version: '3.8'
services:
  prc-cerif:
    build:
      context: .
      dockerfile: Dockerfile
    image: 'prc/prc-cerif:2.4.19'
    container_name: prc-cerif
    hostname: prc-cerif
    volumes:
      - ${SOURCE_FOLDER}:${TARGET_FOLDER}:rw
