//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.4-2 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2014.08.18 at 08:52:34 AM CEST 
//


package cerif;

import java.util.ArrayList;
import java.util.List;

import javax.xml.bind.JAXBElement;
import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlElementRef;
import javax.xml.bind.annotation.XmlElementRefs;
import javax.xml.bind.annotation.XmlSchemaType;
import javax.xml.bind.annotation.XmlType;
import javax.xml.datatype.XMLGregorianCalendar;


/**
 * <p>Java class for cfExpSkills__Type complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType name="cfExpSkills__Type">
 *   &lt;complexContent>
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *       &lt;sequence>
 *         &lt;element name="cfExpSkillsId" type="{urn:xmlns:org:eurocris:cerif-1.6-2}cfId__Type"/>
 *         &lt;element name="cfURI" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/>
 *         &lt;choice maxOccurs="unbounded" minOccurs="0">
 *           &lt;element name="cfName" type="{urn:xmlns:org:eurocris:cerif-1.6-2}cfMLangString__Type"/>
 *           &lt;element name="cfKeyw" type="{urn:xmlns:org:eurocris:cerif-1.6-2}cfMLangString__Type"/>
 *           &lt;element name="cfDescr" type="{urn:xmlns:org:eurocris:cerif-1.6-2}cfMLangString__Type"/>
 *           &lt;element name="cfOrgUnit_ExpSkills">
 *             &lt;complexType>
 *               &lt;complexContent>
 *                 &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *                   &lt;sequence>
 *                     &lt;element name="cfOrgUnitId" type="{urn:xmlns:org:eurocris:cerif-1.6-2}cfId__Type"/>
 *                     &lt;group ref="{urn:xmlns:org:eurocris:cerif-1.6-2}cfCoreClassWithFraction__Group"/>
 *                     &lt;element name="cfAvailability" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/>
 *                     &lt;element name="cfConditions" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/>
 *                     &lt;element name="cfPrice" type="{urn:xmlns:org:eurocris:cerif-1.6-2}cfAmount__Type" minOccurs="0"/>
 *                   &lt;/sequence>
 *                 &lt;/restriction>
 *               &lt;/complexContent>
 *             &lt;/complexType>
 *           &lt;/element>
 *           &lt;element name="cfPers_ExpSkills">
 *             &lt;complexType>
 *               &lt;complexContent>
 *                 &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *                   &lt;sequence>
 *                     &lt;element name="cfPersId" type="{urn:xmlns:org:eurocris:cerif-1.6-2}cfId__Type"/>
 *                     &lt;group ref="{urn:xmlns:org:eurocris:cerif-1.6-2}cfCoreClassWithFraction__Group"/>
 *                     &lt;element name="cfAvailability" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/>
 *                     &lt;element name="cfConditions" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/>
 *                     &lt;element name="cfPrice" type="{urn:xmlns:org:eurocris:cerif-1.6-2}cfAmount__Type" minOccurs="0"/>
 *                   &lt;/sequence>
 *                 &lt;/restriction>
 *               &lt;/complexContent>
 *             &lt;/complexType>
 *           &lt;/element>
 *           &lt;element name="cfExpSkills_Class" type="{urn:xmlns:org:eurocris:cerif-1.6-2}cfCoreClassWithFraction__Type"/>
 *           &lt;element name="cfFedId" type="{urn:xmlns:org:eurocris:cerif-1.6-2}cfFedId__EmbType"/>
 *         &lt;/choice>
 *       &lt;/sequence>
 *     &lt;/restriction>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "cfExpSkills__Type", propOrder = {
    "cfExpSkillsId",
    "cfURI",
    "cfNameOrCfKeywOrCfDescr"
})
public class CfExpSkillsType {

    /**
     * <p>Java class for anonymous complex type.
     * 
     * <p>The following schema fragment specifies the expected content contained within this class.
     * 
     * <pre>
     * &lt;complexType>
     *   &lt;complexContent>
     *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
     *       &lt;sequence>
     *         &lt;element name="cfOrgUnitId" type="{urn:xmlns:org:eurocris:cerif-1.6-2}cfId__Type"/>
     *         &lt;group ref="{urn:xmlns:org:eurocris:cerif-1.6-2}cfCoreClassWithFraction__Group"/>
     *         &lt;element name="cfAvailability" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/>
     *         &lt;element name="cfConditions" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/>
     *         &lt;element name="cfPrice" type="{urn:xmlns:org:eurocris:cerif-1.6-2}cfAmount__Type" minOccurs="0"/>
     *       &lt;/sequence>
     *     &lt;/restriction>
     *   &lt;/complexContent>
     * &lt;/complexType>
     * </pre>
     * 
     * 
     */
    @XmlAccessorType(XmlAccessType.FIELD)
    @XmlType(name = "", propOrder = {
        "cfOrgUnitId",
        "cfClassId",
        "cfClassSchemeId",
        "cfStartDate",
        "cfEndDate",
        "cfFraction",
        "cfAvailability",
        "cfConditions",
        "cfPrice"
    })
    public static class CfOrgUnitExpSkills {

        protected String cfAvailability;
        @XmlElement(required = true)
        protected String cfClassId;
        @XmlElement(required = true)
        protected String cfClassSchemeId;
        protected String cfConditions;
        @XmlSchemaType(name = "date")
        protected XMLGregorianCalendar cfEndDate;
        protected Float cfFraction;
        @XmlElement(required = true)
        protected String cfOrgUnitId;
        protected CfAmountType cfPrice;
        @XmlSchemaType(name = "date")
        protected XMLGregorianCalendar cfStartDate;

        /**
         * Gets the value of the cfAvailability property.
         * 
         * @return
         *     possible object is
         *     {@link String }
         *     
         */
        public String getCfAvailability() {
            return cfAvailability;
        }

        /**
         * Gets the value of the cfClassId property.
         * 
         * @return
         *     possible object is
         *     {@link String }
         *     
         */
        public String getCfClassId() {
            return cfClassId;
        }

        /**
         * Gets the value of the cfClassSchemeId property.
         * 
         * @return
         *     possible object is
         *     {@link String }
         *     
         */
        public String getCfClassSchemeId() {
            return cfClassSchemeId;
        }

        /**
         * Gets the value of the cfConditions property.
         * 
         * @return
         *     possible object is
         *     {@link String }
         *     
         */
        public String getCfConditions() {
            return cfConditions;
        }

        /**
         * Gets the value of the cfEndDate property.
         * 
         * @return
         *     possible object is
         *     {@link XMLGregorianCalendar }
         *     
         */
        public XMLGregorianCalendar getCfEndDate() {
            return cfEndDate;
        }

        /**
         * Gets the value of the cfFraction property.
         * 
         * @return
         *     possible object is
         *     {@link Float }
         *     
         */
        public Float getCfFraction() {
            return cfFraction;
        }

        /**
         * Gets the value of the cfOrgUnitId property.
         * 
         * @return
         *     possible object is
         *     {@link String }
         *     
         */
        public String getCfOrgUnitId() {
            return cfOrgUnitId;
        }

        /**
         * Gets the value of the cfPrice property.
         * 
         * @return
         *     possible object is
         *     {@link CfAmountType }
         *     
         */
        public CfAmountType getCfPrice() {
            return cfPrice;
        }

        /**
         * Gets the value of the cfStartDate property.
         * 
         * @return
         *     possible object is
         *     {@link XMLGregorianCalendar }
         *     
         */
        public XMLGregorianCalendar getCfStartDate() {
            return cfStartDate;
        }

        /**
         * Sets the value of the cfAvailability property.
         * 
         * @param value
         *     allowed object is
         *     {@link String }
         *     
         */
        public void setCfAvailability(String value) {
            this.cfAvailability = value;
        }

        /**
         * Sets the value of the cfClassId property.
         * 
         * @param value
         *     allowed object is
         *     {@link String }
         *     
         */
        public void setCfClassId(String value) {
            this.cfClassId = value;
        }

        /**
         * Sets the value of the cfClassSchemeId property.
         * 
         * @param value
         *     allowed object is
         *     {@link String }
         *     
         */
        public void setCfClassSchemeId(String value) {
            this.cfClassSchemeId = value;
        }

        /**
         * Sets the value of the cfConditions property.
         * 
         * @param value
         *     allowed object is
         *     {@link String }
         *     
         */
        public void setCfConditions(String value) {
            this.cfConditions = value;
        }

        /**
         * Sets the value of the cfEndDate property.
         * 
         * @param value
         *     allowed object is
         *     {@link XMLGregorianCalendar }
         *     
         */
        public void setCfEndDate(XMLGregorianCalendar value) {
            this.cfEndDate = value;
        }

        /**
         * Sets the value of the cfFraction property.
         * 
         * @param value
         *     allowed object is
         *     {@link Float }
         *     
         */
        public void setCfFraction(Float value) {
            this.cfFraction = value;
        }

        /**
         * Sets the value of the cfOrgUnitId property.
         * 
         * @param value
         *     allowed object is
         *     {@link String }
         *     
         */
        public void setCfOrgUnitId(String value) {
            this.cfOrgUnitId = value;
        }

        /**
         * Sets the value of the cfPrice property.
         * 
         * @param value
         *     allowed object is
         *     {@link CfAmountType }
         *     
         */
        public void setCfPrice(CfAmountType value) {
            this.cfPrice = value;
        }

        /**
         * Sets the value of the cfStartDate property.
         * 
         * @param value
         *     allowed object is
         *     {@link XMLGregorianCalendar }
         *     
         */
        public void setCfStartDate(XMLGregorianCalendar value) {
            this.cfStartDate = value;
        }

    }
    /**
     * <p>Java class for anonymous complex type.
     * 
     * <p>The following schema fragment specifies the expected content contained within this class.
     * 
     * <pre>
     * &lt;complexType>
     *   &lt;complexContent>
     *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
     *       &lt;sequence>
     *         &lt;element name="cfPersId" type="{urn:xmlns:org:eurocris:cerif-1.6-2}cfId__Type"/>
     *         &lt;group ref="{urn:xmlns:org:eurocris:cerif-1.6-2}cfCoreClassWithFraction__Group"/>
     *         &lt;element name="cfAvailability" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/>
     *         &lt;element name="cfConditions" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/>
     *         &lt;element name="cfPrice" type="{urn:xmlns:org:eurocris:cerif-1.6-2}cfAmount__Type" minOccurs="0"/>
     *       &lt;/sequence>
     *     &lt;/restriction>
     *   &lt;/complexContent>
     * &lt;/complexType>
     * </pre>
     * 
     * 
     */
    @XmlAccessorType(XmlAccessType.FIELD)
    @XmlType(name = "", propOrder = {
        "cfPersId",
        "cfClassId",
        "cfClassSchemeId",
        "cfStartDate",
        "cfEndDate",
        "cfFraction",
        "cfAvailability",
        "cfConditions",
        "cfPrice"
    })
    public static class CfPersExpSkills {

        protected String cfAvailability;
        @XmlElement(required = true)
        protected String cfClassId;
        @XmlElement(required = true)
        protected String cfClassSchemeId;
        protected String cfConditions;
        @XmlSchemaType(name = "date")
        protected XMLGregorianCalendar cfEndDate;
        protected Float cfFraction;
        @XmlElement(required = true)
        protected String cfPersId;
        protected CfAmountType cfPrice;
        @XmlSchemaType(name = "date")
        protected XMLGregorianCalendar cfStartDate;

        /**
         * Gets the value of the cfAvailability property.
         * 
         * @return
         *     possible object is
         *     {@link String }
         *     
         */
        public String getCfAvailability() {
            return cfAvailability;
        }

        /**
         * Gets the value of the cfClassId property.
         * 
         * @return
         *     possible object is
         *     {@link String }
         *     
         */
        public String getCfClassId() {
            return cfClassId;
        }

        /**
         * Gets the value of the cfClassSchemeId property.
         * 
         * @return
         *     possible object is
         *     {@link String }
         *     
         */
        public String getCfClassSchemeId() {
            return cfClassSchemeId;
        }

        /**
         * Gets the value of the cfConditions property.
         * 
         * @return
         *     possible object is
         *     {@link String }
         *     
         */
        public String getCfConditions() {
            return cfConditions;
        }

        /**
         * Gets the value of the cfEndDate property.
         * 
         * @return
         *     possible object is
         *     {@link XMLGregorianCalendar }
         *     
         */
        public XMLGregorianCalendar getCfEndDate() {
            return cfEndDate;
        }

        /**
         * Gets the value of the cfFraction property.
         * 
         * @return
         *     possible object is
         *     {@link Float }
         *     
         */
        public Float getCfFraction() {
            return cfFraction;
        }

        /**
         * Gets the value of the cfPersId property.
         * 
         * @return
         *     possible object is
         *     {@link String }
         *     
         */
        public String getCfPersId() {
            return cfPersId;
        }

        /**
         * Gets the value of the cfPrice property.
         * 
         * @return
         *     possible object is
         *     {@link CfAmountType }
         *     
         */
        public CfAmountType getCfPrice() {
            return cfPrice;
        }

        /**
         * Gets the value of the cfStartDate property.
         * 
         * @return
         *     possible object is
         *     {@link XMLGregorianCalendar }
         *     
         */
        public XMLGregorianCalendar getCfStartDate() {
            return cfStartDate;
        }

        /**
         * Sets the value of the cfAvailability property.
         * 
         * @param value
         *     allowed object is
         *     {@link String }
         *     
         */
        public void setCfAvailability(String value) {
            this.cfAvailability = value;
        }

        /**
         * Sets the value of the cfClassId property.
         * 
         * @param value
         *     allowed object is
         *     {@link String }
         *     
         */
        public void setCfClassId(String value) {
            this.cfClassId = value;
        }

        /**
         * Sets the value of the cfClassSchemeId property.
         * 
         * @param value
         *     allowed object is
         *     {@link String }
         *     
         */
        public void setCfClassSchemeId(String value) {
            this.cfClassSchemeId = value;
        }

        /**
         * Sets the value of the cfConditions property.
         * 
         * @param value
         *     allowed object is
         *     {@link String }
         *     
         */
        public void setCfConditions(String value) {
            this.cfConditions = value;
        }

        /**
         * Sets the value of the cfEndDate property.
         * 
         * @param value
         *     allowed object is
         *     {@link XMLGregorianCalendar }
         *     
         */
        public void setCfEndDate(XMLGregorianCalendar value) {
            this.cfEndDate = value;
        }

        /**
         * Sets the value of the cfFraction property.
         * 
         * @param value
         *     allowed object is
         *     {@link Float }
         *     
         */
        public void setCfFraction(Float value) {
            this.cfFraction = value;
        }

        /**
         * Sets the value of the cfPersId property.
         * 
         * @param value
         *     allowed object is
         *     {@link String }
         *     
         */
        public void setCfPersId(String value) {
            this.cfPersId = value;
        }

        /**
         * Sets the value of the cfPrice property.
         * 
         * @param value
         *     allowed object is
         *     {@link CfAmountType }
         *     
         */
        public void setCfPrice(CfAmountType value) {
            this.cfPrice = value;
        }

        /**
         * Sets the value of the cfStartDate property.
         * 
         * @param value
         *     allowed object is
         *     {@link XMLGregorianCalendar }
         *     
         */
        public void setCfStartDate(XMLGregorianCalendar value) {
            this.cfStartDate = value;
        }

    }
    @XmlElement(required = true)
    protected String cfExpSkillsId;

    @XmlElementRefs({
        @XmlElementRef(name = "cfFedId", namespace = "urn:xmlns:org:eurocris:cerif-1.6-2", type = JAXBElement.class, required = false),
        @XmlElementRef(name = "cfExpSkills_Class", namespace = "urn:xmlns:org:eurocris:cerif-1.6-2", type = JAXBElement.class, required = false),
        @XmlElementRef(name = "cfOrgUnit_ExpSkills", namespace = "urn:xmlns:org:eurocris:cerif-1.6-2", type = JAXBElement.class, required = false),
        @XmlElementRef(name = "cfDescr", namespace = "urn:xmlns:org:eurocris:cerif-1.6-2", type = JAXBElement.class, required = false),
        @XmlElementRef(name = "cfKeyw", namespace = "urn:xmlns:org:eurocris:cerif-1.6-2", type = JAXBElement.class, required = false),
        @XmlElementRef(name = "cfPers_ExpSkills", namespace = "urn:xmlns:org:eurocris:cerif-1.6-2", type = JAXBElement.class, required = false),
        @XmlElementRef(name = "cfName", namespace = "urn:xmlns:org:eurocris:cerif-1.6-2", type = JAXBElement.class, required = false)
    })
    protected List<JAXBElement<?>> cfNameOrCfKeywOrCfDescr;

    protected String cfURI;

    /**
     * Gets the value of the cfExpSkillsId property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getCfExpSkillsId() {
        return cfExpSkillsId;
    }

    /**
     * Gets the value of the cfNameOrCfKeywOrCfDescr property.
     * 
     * <p>
     * This accessor method returns a reference to the live list,
     * not a snapshot. Therefore any modification you make to the
     * returned list will be present inside the JAXB object.
     * This is why there is not a <CODE>set</CODE> method for the cfNameOrCfKeywOrCfDescr property.
     * 
     * <p>
     * For example, to add a new item, do as follows:
     * <pre>
     *    getCfNameOrCfKeywOrCfDescr().add(newItem);
     * </pre>
     * 
     * 
     * <p>
     * Objects of the following type(s) are allowed in the list
     * {@link JAXBElement }{@code <}{@link CfFedIdEmbType }{@code >}
     * {@link JAXBElement }{@code <}{@link CfCoreClassWithFractionType }{@code >}
     * {@link JAXBElement }{@code <}{@link CfExpSkillsType.CfOrgUnitExpSkills }{@code >}
     * {@link JAXBElement }{@code <}{@link CfMLangStringType }{@code >}
     * {@link JAXBElement }{@code <}{@link CfMLangStringType }{@code >}
     * {@link JAXBElement }{@code <}{@link CfExpSkillsType.CfPersExpSkills }{@code >}
     * {@link JAXBElement }{@code <}{@link CfMLangStringType }{@code >}
     * 
     * 
     */
    public List<JAXBElement<?>> getCfNameOrCfKeywOrCfDescr() {
        if (cfNameOrCfKeywOrCfDescr == null) {
            cfNameOrCfKeywOrCfDescr = new ArrayList<JAXBElement<?>>();
        }
        return this.cfNameOrCfKeywOrCfDescr;
    }

    /**
     * Gets the value of the cfURI property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getCfURI() {
        return cfURI;
    }


    /**
     * Sets the value of the cfExpSkillsId property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setCfExpSkillsId(String value) {
        this.cfExpSkillsId = value;
    }


    /**
     * Sets the value of the cfURI property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setCfURI(String value) {
        this.cfURI = value;
    }

}
