//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.4-2 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2014.08.18 at 08:52:34 AM CEST 
//

@javax.xml.bind.annotation.XmlSchema(namespace = "urn:xmlns:org:eurocris:cerif-1.6-2", elementFormDefault = javax.xml.bind.annotation.XmlNsForm.QUALIFIED)
package cerif;
